name: tezster_dart
description: A flutter package which provides the functionalities to play around
  with tezos dApps
version: 2.1.1
homepage: https://github.com/Tezsure/tezster_dart
repository: https://github.com/Tezsure/tezster_dart
issue_tracker: https://github.com/Tezsure/tezster_dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bip39: ^1.0.6
  password_hash:
    path: ../dart-password-hash
  blake2b:
    path: ../blake2b
  bs58check: ^1.0.2
  convert: ^3.0.0
  crypto: ^3.0.1
  flutter_sodium: ^0.2.0
  unorm_dart: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
